site_name: DevOps Documentation
site_url: https://docs.snappic.xyz/
site_author: Ashley Kleynhans & DevOps Team
repo_url: https://github.com/MushroomCloud/devops-docs
edit_uri: _edit/master/docs/
site_description: DevOps Engineers Documentation
copyright: Copyright © 2022 SnapPic DevOps team
nav:
- Home: 'index.md'
- Applications:
    - Ansible:
        - 'Overview': app/ansible/overview.md
        - 'Getting Started': app/ansible/quickstart.md
        - 'Contributing': app/ansible/contributing.md
        - 'Inventory': app/ansible/inventory.md
        - 'Group Vars': app/ansible/group-vars.md
        - 'Local dev setup': app/ansible/local-development-setup.md
        - 'Troubleshooting': app/ansible/troubleshooting.md
        - 'Tips': app/ansible/tips.md
        - 'Project Structure': app/ansible/project-structure.md
    - AWS:
        - 'Overview': app/aws/overview.md
- Standards:
    - standard/naming.md
- Procedures:
    - 'Onboarding DevOps member': procedure/onboarding.md
    - Git:
        - procedure/git-branching.md
        - procedure/git-signing.md
- Team:
    - team/about.md
    - team/devops.md
- About DevOps Docs:
    - docs/contributing.md
    - docs/basic-editing.md
    - docs/advanced-editing.md
    - docs/quickstart-venv.md
    - Writing:
        - docs/writing/sheet.md
        - docs/writing/mermaid.md
    - docs/why.md
    - docs/compare.md
    - docs/CHANGELOG.md
theme:
  name: material
  font:
    text: 'Source Sans Pro'
    code: 'Roboto Mono'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate  # dark
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  static_templates:
    - 404.html
  icon:
    logo: fontawesome/solid/book-open-reader
    repo: fontawesome/brands/git-alt
  custom_dir: overrides
plugins:
  - search
  # - with-pdf:
  #     output_path: pdf/devops-documentation.pdf
  #     cover_logo: img/sre-dude.jpg
  #     cover_subtitle: DevOps Engineering Book
  #     enabled_if_env: ENABLE_PDF_EXPORT
  - redirects:
      redirect_maps:
        'app/ansible.md': app/ansible/overview.md
        'app/aws.md': app/aws/overview.md
markdown_extensions:
    - extra
    - toc:
          permalink: '#'
    - pymdownx.caret
    - pymdownx.tilde
    - pymdownx.mark
    - admonition
    - pymdownx.details
    - pymdownx.tabbed
    - codehilite:
          guess_lang: false
          linenums: false
    - pymdownx.inlinehilite
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        # emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
          custom_checkbox: true
    - markdown_blockdiag:
          format: svg
    - markdown_include.include

extra:
  social:
    - icon: fontawesome/solid/book-open-reader
      link: https://docs.snappic.xyz/
    - icon: fontawesome/brands/git-square
      link: https://github.com/MushroomCloud/devops-docs
    - icon: fontawesome/solid/envelope
      link: mailto:connect-it-ops@fnb.co.za

extra_javascript:
  - https://unpkg.com/mermaid@8.5.2/dist/mermaid.min.js

extra_css:
  - stylesheets/extra.css
