site_name: DevOps Documentation
site_url: http://docs.snappic.xyz/
site_author: Ashley Kleynhans & DevOps Team
repo_url: https://github.com/MushroomCloud/DevopsDocs
edit_uri: edit/main/docs/
site_description: DevOps Engineers Documentation
copyright: Copyright © 2022 SnapPic DevOps team
nav:
- Home: 'index.md'
- About DevOps Docs:
    - docs/contributing.md
    - docs/basic-editing.md
    - docs/advanced-editing.md
    - docs/quickstart-venv.md
    #- Writing:
        #- docs/writing/sheet.md
        #- docs/writing/mermaid.md
    - docs/why.md
    - docs/compare.md
    - docs/CHANGELOG.md
- Applications:
    - 'Background Workers':
        - 'Overview': app/backgroundworkers/overview.md
    - Blog:
        - 'Overview': app/blog/overview.md
        - 'Troubleshooting': app/blog/troubleshooting.md
    - Caching:
        - 'Overview': app/caching/overview.md
        - 'Memcached':
            - 'Overview': app/caching/memcached/overview.md
        - 'Redis':
            - 'Overview': app/caching/redis/overview.md
            - 'Deploying': app/caching/redis/deploying.md
            - 'Upgrading': app/caching/redis/upgrading.md
        - 'Troubleshooting': app/caching/troubleshooting.md
    - Consul:
        - 'Overview': app/consul/overview.md
        - 'Recovering': app/consul/recovering.md
        - 'Troubleshooting': app/consul/troubleshooting.md
    - 'Events Dashboard':
        - 'Overview': app/eventsdashboard/overview.md
    - 'Heavy Duty Workers':
        - 'Overview': app/heavydutyworkers/overview.md
    - 'Image AI':
        - 'Overview': app/imageai/overview.md
        - 'RabbitMQ Consumers': app/imageai/rabbitmq-consumers.md
        - 'REST API': app/imageai/rest-api.md
        - 'Web App': app/imageai/web-app.md
        - 'RunPod Serverless Workers':
            - 'Overview': app/imageai/runpod-workers/overview.md
            - 'A1111':
                - 'Overview': app/imageai/runpod-workers/a1111/overview.md
                - 'Get ControlNet Models': app/imageai/runpod-workers/a1111/get-controlnet-models.md
                - 'Get Embeddings': app/imageai/runpod-workers/a1111/get-embeddings.md
                - 'Get Face Restorers': app/imageai/runpod-workers/a1111/get-face-restorers.md
                - 'Get Hypernetworks': app/imageai/runpod-workers/a1111/get-hypernetworks.md
                - 'Get Loras': app/imageai/runpod-workers/a1111/get-loras.md
                - 'Get Memory': app/imageai/runpod-workers/a1111/get-memory.md
                - 'Get Models': app/imageai/runpod-workers/a1111/get-models.md
                - 'Get Options': app/imageai/runpod-workers/a1111/get-options.md
                - 'Get Prompt Styles': app/imageai/runpod-workers/a1111/get-prompt-styles.md
                - 'Get Real-ESRGAN Models': app/imageai/runpod-workers/a1111/get-realesrgan-models.md
                - 'Get Samplers': app/imageai/runpod-workers/a1111/get-samplers.md
                - 'Get Script Info': app/imageai/runpod-workers/a1111/get-script-info.md
                - 'Get Scripts': app/imageai/runpod-workers/a1111/get-scripts.md
                - 'Get Upscalers': app/imageai/runpod-workers/a1111/get-upscalers.md
                - 'Get VAE': app/imageai/runpod-workers/a1111/get-vae.md
                - 'Image to Image': app/imageai/runpod-workers/a1111/img2img.md
                - 'Image to Image with ControlNet': app/imageai/runpod-workers/a1111/img2img-controlnet.md
                - 'Refresh Checkpoints': app/imageai/runpod-workers/a1111/refresh-checkpoints.md
                - 'Refresh Loras': app/imageai/runpod-workers/a1111/refresh-loras.md
                - 'Set Model': app/imageai/runpod-workers/a1111/set-model.md
                - 'Set VAE': app/imageai/runpod-workers/a1111/set-vae.md
                - 'Text to Image': app/imageai/runpod-workers/a1111/txt2img.md
            - 'ComfyUI':
                - 'Overview': app/imageai/runpod-workers/comfyui/overview.md
            - 'Face Swap':
                - 'Overview': app/imageai/runpod-workers/inswapper/overview.md
                - 'Swap as many source faces as possible into as many target faces as possible': app/imageai/runpod-workers/inswapper/swap-as-many-faces-as-possible.md
                - 'Swap a single source face into a specific target face in a target image containing multiple faces': app/imageai/runpod-workers/inswapper/swap-single-source-face-into-specific-target-face.md
                - 'Swap two faces from source image into 2 specific target faces in a target image containing multiple faces': app/imageai/runpod-workers/inswapper/swap-specific-faces-into-specific-target-faces.md
                - 'Swap two specific faces from source image containing multiple faces into 2 specific target faces in a target image containing multiple faces': app/imageai/runpod-workers/inswapper/swap-two-faces-into-specific-target-faces.md
            - 'InstantID':
                - 'Overview': app/imageai/runpod-workers/instantid/overview.md
            - 'Upscaling':
                - 'Overview':  app/imageai/runpod-workers/upscaling/overview.md
            - 'Webhook': app/imageai/runpod-workers/webhook.md
    - MySQL:
        - 'Overview': app/mysql/overview.md
        - 'Lifecycle': app/mysql/lifecycle.md
        - 'Configuring': app/mysql/configuring.md
        - 'Upgrading': app/mysql/upgrading.md
        - 'Troubleshooting': app/mysql/troubleshooting.md
    - OpenResty:
        - 'Overview': app/openresty/overview.md
        - 'Maintenance': app/openresty/maintenance.md
        - 'Troubleshooting': app/openresty/troubleshooting.md
    - RabbitMQ:
        - 'Overview': app/rabbitmq/overview.md
        - 'Consumers': app/rabbitmq/consumers.md
        - 'Deploying': app/rabbitmq/deploying.md
        - 'Monitoring': app/rabbitmq/monitoring.md
        - 'Rebuilding': app/rabbitmq/rebuilding.md
        - 'Useful Commands': app/rabbitmq/useful-commands.md
        - 'Troubleshooting': app/rabbitmq/troubleshooting.md
    - 'Session Archiver':
        - 'Overview': app/sessionarchiver/overview.md
    - Slideshow:
        - 'Overview': app/slideshow/overview.md
        - 'Deploying': app/slideshow/deploying.md
    - VideoFX:
        - 'Overview': app/videofx/overview.md
        - 'Consumers': app/videofx/consumers.md
        - 'Processors': app/videofx/processors.md
        - 'Preview': app/videofx/preview.md
        - 'Troubleshooting': app/videofx/troubleshooting.md
    - Website:
        - 'Overview': app/website/overview.md
    - YOURLS:
        - 'Overview': app/yourls/overview.md
        - 'Upgrading': app/yourls/upgrading.md
        - 'Testing': app/yourls/testing.md
        - 'Troubleshooting': app/yourls/troubleshooting.md
- Environments:
    - Overview: env/overview.md
    - Prod:
        - 'Overview': env/prod/overview.md
    - Test:
        - 'Overview': env/test/overview.md
    - Cosmos:
        - 'Overview': env/cosmos/overview.md
    - Universe:
        - 'Overview': env/universe/overview.md

- Incidents:
    - 2023:
        - 'RabbitMQ (30 April 2023)': incident/2023/30-april-rabbitmq.md
        - 'Route53 (30 April 2023)': incident/2023/30-april-route53.md
        - 'Create Zip Consumer (3 May 2023)': incident/2023/3-may-create-zip.md
- Infrastructure:
    - Overview: infra/overview.md
    - Ansible:
        - 'Overview': infra/ansible/overview.md
        - 'Getting Started': infra/ansible/quickstart.md
        - 'Contributing': infra/ansible/contributing.md
        - 'Inventory': infra/ansible/inventory.md
        - 'Group Vars': infra/ansible/group-vars.md
        - 'Local dev setup': infra/ansible/local-development-setup.md
        - 'Troubleshooting': infra/ansible/troubleshooting.md
        - 'Tips': infra/ansible/tips.md
        - 'Project Structure': infra/ansible/project-structure.md
    - AWS:
        - 'Overview': infra/aws/overview.md
        - 'EC2 Instance Types': infra/aws/ec2-instance-types.md
        - ECS:
            - infra/aws/ecs/overview.md
            - infra/aws/ecs/ecs-container-shell.md
        - 'Lambda Functions': infra/aws/lambda-functions.md
        - S3:
            - infra/aws/s3/overview.md
            - infra/aws/s3/access-logs.md
    - Elastic:
        - 'Overview': infra/elastic/overview.md
        - 'Troubleshooting': infra/elastic/troubleshooting.md
        - 'Upgrading': infra/elastic/upgrading.md
    - GCP:
        - 'Overview': infra/gcp/overview.md
        - 'Changes': infra/gcp/changes.md
        - 'Troubleshooting': infra/gcp/troubleshooting.md
    - Github:
        - 'Overview': infra/github/overview.md
    - Jenkins:
        - 'Overview': infra/jenkins/overview.md
        - 'Troubleshooting': infra/jenkins/troubleshooting.md
    - 'Mac Minis':
        - 'Overview': infra/mac/overview.md
        - 'Setup': infra/mac/setup.md
        - 'Updating Firewall Rules': infra/mac/firewall.md
        - 'Upgrading': infra/mac/upgrading.md
    - Security:
        - 'Overview': infra/security/overview.md
        - 'Firewall':
            - 'Overview': infra/security/firewall/overview.md
            - 'AWS':
                - 'Overview': infra/security/firewall/aws/overview.md
                - 'NFTables': infra/security/firewall/aws/nftables.md
                - 'Security Groups': infra/security/firewall/aws/security-groups.md
            - 'Mac Minis':
                - 'Overview': infra/security/firewall/mac/overview.md
        - 'Load Balancer': infra/security/load-balancer.md
        - 'Network ACL': infra/security/network-acl.md
        - 'WAF':
            - 'Overview': infra/security/waf/overview.md
            - 'Web ACLs': infra/security/waf/web-acl.md
            - 'IP Sets': infra/security/waf/ip-set.md
            - 'Regex Pattern Sets': infra/security/waf/regex-pattern-set.md
            - 'Rule Groups': infra/security/waf/rule-group.md
    - Spinnaker:
        - 'Overview': infra/spinnaker/overview.md
        - 'Auto Scaling': infra/spinnaker/autoscaling.md
        - 'Cloning a Server Group': infra/spinnaker/cloning.md
        - 'Strategies': infra/spinnaker/strategies.md
        - 'Troubleshooting': infra/spinnaker/troubleshooting.md
    - SSL Certs:
        - 'Overview': infra/ssl/overview.md
        - 'Requesting': infra/ssl/requesting.md
        - 'Installing': infra/ssl/installing.md
        - 'Monitoring': infra/ssl/monitoring.md
        - 'Troubleshooting': infra/ssl/troubleshooting.md
    - Terraform:
        - 'Overview': infra/terraform/overview.md
        - 'Getting Started': infra/terraform/getting-started.md
        - 'Upgrading': infra/terraform/upgrading.md
        - 'Restoring State from Backup': infra/terraform/restoring-state.md
        - 'Troubleshooting': infra/terraform/troubleshooting.md
    - Monitoring:
        - 'Alertmanager':
            - 'Overview': infra/monitoring/alertmanager/overview.md
        - 'CheckMK':
            - 'Bulk Discovery': infra/monitoring/checkmk/bulk-discovery.md
            - 'Installing CheckMK Agent on macOS': infra/monitoring/checkmk/installing-on-macos.md
            - 'Overview': infra/monitoring/checkmk/overview.md
            - 'Reinstalling CheckMK Agent': infra/monitoring/checkmk/reinstalling.md
            - 'Troubleshooting': infra/monitoring/checkmk/troubleshooting.md
            - 'Upgrading CheckMK Server': infra/monitoring/checkmk/upgrading.md
        - 'Grafana':
            - 'Overview': infra/monitoring/grafana/overview.md
        - 'InfluxDB':
            - 'Overview': infra/monitoring/influxdb/overview.md
        - 'Loki':
            - 'Overview': infra/monitoring/loki/overview.md
        - 'PagerDuty':
            - 'Overview': infra/monitoring/pagerduty/overview.md
        - 'Prometheus':
            - 'Overview': infra/monitoring/prometheus/overview.md
            - 'Exporters': infra/monitoring/prometheus/exporters.md
    - RunPod:
        - 'Overview': infra/runpod/overview.md
    - Vercel:
        - 'Overview': infra/vercel/overview.md
    - VPN:
        - 'Overview': infra/vpn/overview.md
        - 'Troubleshooting': infra/vpn/troubleshooting.md
- Lists:
    - 'List of Contacts': list/contacts.md
    - 'List of Domains': list/domains.md
    - 'List of Product Tools': list/tools.md
    - 'List of Static IPs': list/ips.md
    - 'List of Useful Links': list/urls.md
    - 'List of VPN Servers': list/vpns.md
    - 'List of Webhooks': list/webhooks.md
- Procedures:
    - Git:
        - procedure/dev-workflow.md
        - procedure/git-branching.md
        - procedure/git-signing.md
    - 'Onboarding DevOps member': procedure/onboarding.md
    - Production Deployments:
        - procedure/times.md
        - procedure/prod-deployments.md
- Projects:
    - 'Symfony Upgrade':
        - 'Overview': project/symfony-upgrade/overview.md
        - 'Upgrading PHP': project/symfony-upgrade/upgrading-php.md
- Standards:
    - standard/naming.md
- Team:
    - team/about.md
    - team/devops.md
- Tools:
    - Load Testing:
        - tool/load-testing/overview.md
        - tool/load-testing/session-upload.md
theme:
  name: material
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate  # dark
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  static_templates:
    - 404.html
  icon:
    logo: fontawesome/solid/book-open-reader
    repo: fontawesome/brands/git-alt
  custom_dir: overrides
plugins:
  - search
  - with-pdf:
      output_path: pdf/devops-documentation.pdf
      cover_logo: img/sre-dude.jpg
      cover_subtitle: DevOps Engineering Book
      enabled_if_env: ENABLE_PDF_EXPORT
  - redirects:
      redirect_maps:
        'app/ansible.md': infra/ansible/overview.md
        'app/aws.md': infra/aws/overview.md
markdown_extensions:
    - extra
    - toc:
          permalink: '#'
    - pymdownx.caret
    - pymdownx.tilde
    - pymdownx.mark
    - admonition
    - pymdownx.details
    - pymdownx.tabbed:
        alternate_style: true
    - codehilite:
          guess_lang: false
          linenums: false
    - pymdownx.inlinehilite
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_div_format
    - pymdownx.betterem:
          smart_enable: all
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        # emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.keys
    - pymdownx.smartsymbols
    - pymdownx.snippets
    - pymdownx.tasklist:
          custom_checkbox: true
          clickable_checkbox: true
    - markdown_include.include

extra:
  social:
    - icon: fontawesome/solid/book-open-reader
      link: https://docs.snappic.xyz/
    - icon: fontawesome/brands/github
      link: https://github.com/MushroomCloud/DevopsDocs
    - icon: fontawesome/solid/envelope
      link: mailto:ashley@getsnappic.com

extra_javascript:
  - https://unpkg.com/mermaid@8.5.2/dist/mermaid.min.js

extra_css:
  - stylesheets/extra.css
